# Generated by Django 4.1.1 on 2022-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wormgateWeb', '0002_alter_personaje_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=models.CharField(max_length=530),
        ),
    ]
