# Generated by Django 4.1.1 on 2022-10-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('formato', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
