# Generated by Django 4.0.1 on 2022-10-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprar', '0002_alter_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='comprar'),
        ),
    ]
