# Generated by Django 4.0.1 on 2022-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprar', '0004_formato_producto_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
        migrations.AlterField(
            model_name='producto',
            name='formato',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Formato',
        ),
    ]
