# Generated by Django 4.0.1 on 2022-11-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprar', '0005_remove_producto_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=32),
        ),
    ]
